REACT_APP_API_KEY=AIzaSyBn6kZe487RsSon8XSetDp_BS17ZbGeADM
REACT_APP_AUTHDOMAIN=fir-react-chat-5c3c1.firebaseapp.com
REACT_APP_PROJECTID="fir-react-chat-5c3c1"
REACT_APP_STORAGEBUCKET=fir-react-chat-5c3c1.appspot.com
REACT_APP_MESSAGESENDERID=650361768706
REACT_APP_APPID=1:650361768706:web:291e16548bea513cc1d01b